import type { ReportInput } from "../../src/server/schemas";

/** Fictional company, used for previews and protocol tests. */
export const SAMPLE_REPORT: ReportInput = {
  company: {
    name: "Lumen Freight Technologies",
    legalName: "Lumen Freight Technologies Ltd",
    website: "https://www.lumenfreight.example",
    tagline: "Real-time visibility and automation platform for mid-market freight forwarders",
    description:
      "Lumen Freight sells a SaaS platform that gives freight forwarders live shipment visibility, automated customs documentation and customer portals. Founded in 2016 in Rotterdam, it serves around 640 forwarders across Europe and North America and has been expanding into the US since 2024.",
    hq: "Rotterdam, Netherlands",
    founded: "2016",
    industry: "Logistics software",
    ownership: "private",
    stage: "Series C",
    employees: "~720",
    revenue: "€84M ARR (Jun 2026, company reported)",
    valuation: "€1.1B (Series C, Mar 2026)",
    ceo: "Marieke van der Berg",
  },
  meta: {
    purpose: "sales",
    purposeLabel: "Sales research for Priya Nair (Helios Payroll)",
    profileId: "sales-priya-1a2b",
    researchedAt: "2026-10-04",
    depth: "deep",
    overallConfidence: "medium",
    confidenceNote: "Private company: revenue and headcount come from company statements and press; margins are estimates.",
    searchesRun: 31,
  },
  summary: {
    headline: "Strong-fit account with a live trigger: a 180-person US expansion is straining payroll and benefits across five new states.",
    bullets: [
      "€84M ARR growing ~45% a year; Series C of €140M closed in March 2026 led by Atomico, giving ample budget for back-office tooling.",
      "Headcount jumped from 410 to ~720 in 18 months, with 180 hires planned in the US by mid-2027 across Texas, Illinois and New Jersey.",
      "A new CFO (Jonas Keller, ex-Adyen) started in May 2026 and has publicly prioritised 'finance and people systems that scale across entities'.",
      "Payroll today runs on a Dutch provider plus spreadsheets for US contractors; two Glassdoor reviews in 2026 complain about late expense and bonus payments.",
      "Procurement is centralised under the COO; the VP People (Sofia Marin) owns HR systems and has championed two vendor switches before.",
    ],
    whyItMatters: [
      "Multi-entity, multi-state payroll is exactly the pain Helios solves; the US ramp creates a 6-9 month window before they lock in a US-only provider.",
      "Budget is not the blocker: the Series C and the CFO's stated agenda make a platform purchase plausible this fiscal year (FY ends December).",
      "The VP People is a proven champion; the CFO is the economic buyer and is new, so he will want quick wins he can report to the board.",
    ],
    recommendation: "Open with the VP People on the US payroll complexity angle this month, then bring the CFO a cost-and-compliance business case before Q4 planning.",
  },
  fit: {
    score: 82,
    label: "Strong fit",
    rationale: "Industry, size, growth stage and an active trigger all match the Helios ICP. Geography is split (EU HQ, US expansion), which suits Helios's multi-country coverage but means a Dutch incumbent to displace.",
    criteria: [
      { name: "Industry match", score: 85, assessment: "Logistics SaaS is a named target vertical; asset-light, white-collar workforce.", sourceIds: [1] },
      { name: "Company size", score: 90, assessment: "~720 employees, squarely in the 500-2,000 sweet spot.", sourceIds: [2, 6] },
      { name: "Geography", score: 70, assessment: "Netherlands HQ with US, UK and German entities; Helios covers all four.", sourceIds: [1, 4] },
      { name: "Buyer access", score: 80, assessment: "CFO and VP People identified with public profiles and recent talks.", sourceIds: [5, 7] },
      { name: "Budget signals", score: 88, assessment: "€140M raise in March 2026; CFO agenda includes systems.", sourceIds: [3, 5] },
      { name: "Timing and triggers", score: 92, assessment: "US expansion and new CFO within the last 6 months.", sourceIds: [4, 5] },
      { name: "Incumbent exposure", score: 65, assessment: "Dutch payroll provider with a contract likely renewing Q1 2027; spreadsheets for US.", sourceIds: [8, 9] },
      { name: "Strategic alignment", score: 84, assessment: "Scaling back-office systems is an explicit post-raise priority.", sourceIds: [5] },
    ],
  },
  metrics: [
    { label: "ARR", value: "€84M", change: "+45% YoY", trend: "up", note: "company reported, Jun 2026", sourceIds: [3] },
    { label: "Employees", value: "~720", change: "+76% in 18 months", trend: "up", sourceIds: [2, 6] },
    { label: "Total funding", value: "€236M", note: "Series C €140M, Mar 2026", sourceIds: [3] },
    { label: "Customers", value: "640+", change: "+120 in 2025", trend: "up", sourceIds: [1, 3] },
    { label: "Net revenue retention", value: "118%", note: "stated at Series C", sourceIds: [3] },
    { label: "US headcount plan", value: "180 hires", note: "by mid-2027", trend: "up", sourceIds: [4] },
  ],
  timeline: [
    { date: "2026-09-18", title: "Opens Chicago office, third US location", description: "Follows Austin (2024) and Newark (2025); 60 roles posted across sales, support and implementation.", category: "expansion", impact: "positive", relevance: "high", sourceIds: [4] },
    { date: "2026-07-02", title: "Launches customs automation for US imports", description: "First product built by the US team; signals commitment to the market.", category: "product", impact: "positive", relevance: "medium", sourceIds: [10] },
    { date: "2026-05-12", title: "Jonas Keller joins as CFO", description: "Previously VP Finance at Adyen. In a podcast interview he named 'finance and people systems that scale across entities' as a first-year priority.", category: "leadership", impact: "positive", relevance: "high", sourceIds: [5] },
    { date: "2026-03-20", title: "Series C: €140M led by Atomico", description: "Valuation €1.1B. Use of proceeds: US expansion, product, and 'operational foundations'.", category: "funding", impact: "positive", relevance: "high", sourceIds: [3] },
    { date: "2026-02-04", title: "Glassdoor reviews flag late bonus payments", description: "Two reviews from US employees mention bonuses and expenses paid weeks late 'because payroll is run from the Netherlands'.", category: "other", impact: "negative", relevance: "high", sourceIds: [8] },
    { date: "2025-11-15", title: "Acquires Clearpath Customs (UK)", description: "Adds 45 employees and a UK entity; integration still in progress per job posts.", category: "ma", impact: "neutral", relevance: "medium", sourceIds: [11] },
    { date: "2025-06-30", title: "Headcount passes 500", category: "hiring", impact: "positive", relevance: "medium", sourceIds: [6] },
  ],
  financials: {
    summary: "Revenue roughly doubled between 2024 and 2026 on the back of US expansion and the Clearpath acquisition. The company says it is 'close to break-even' but has not published margins; with ~720 staff and €84M ARR, operating costs are likely near revenue.",
    series: [
      { name: "ARR", unit: "EUR", currency: "EUR", points: [{ period: "2022", value: 14_000_000 }, { period: "2023", value: 26_000_000 }, { period: "2024", value: 41_000_000 }, { period: "2025", value: 58_000_000 }, { period: "2026", value: 84_000_000, estimate: true }], sourceIds: [3, 12] },
      { name: "Headcount", unit: "people", points: [{ period: "2022", value: 190 }, { period: "2023", value: 290 }, { period: "2024", value: 410 }, { period: "2025", value: 560 }, { period: "2026", value: 720 }], sourceIds: [6] },
    ],
    funding: [
      { date: "2026-03", round: "Series C", amount: "€140M", investors: ["Atomico", "Index Ventures", "Northzone"], valuation: "€1.1B", sourceIds: [3] },
      { date: "2024-01", round: "Series B", amount: "€68M", investors: ["Index Ventures", "Northzone"], sourceIds: [12] },
      { date: "2021-09", round: "Series A", amount: "€24M", investors: ["Northzone", "Peak Capital"], sourceIds: [12] },
    ],
  },
  people: [
    { name: "Marieke van der Berg", title: "Co-founder and CEO", role: "ceo", since: "2016", background: "Ex-Maersk product lead; engineer by training.", relevance: "Sets the US-first strategy; unlikely to be involved in a payroll decision but shapes urgency.", sourceIds: [1] },
    { name: "Jonas Keller", title: "Chief Financial Officer", role: "executive", since: "May 2026", background: "Previously VP Finance at Adyen, where he led the finance systems overhaul.", relevance: "Economic buyer. New in role, publicly committed to scalable finance and people systems.", sourceIds: [5] },
    { name: "Sofia Marin", title: "VP People", role: "executive", since: "2023", background: "Scaled People ops at Mollie from 300 to 900 employees.", relevance: "Likely champion; owns HRIS and payroll vendor relationships; replaced the HRIS in 2024.", sourceIds: [7] },
    { name: "Daniel Oyelaran", title: "COO", role: "executive", since: "2022", background: "Ex-Flexport operations.", relevance: "Owns procurement; will sign off on vendor consolidation.", sourceIds: [1] },
    { name: "Hannah Weiss", title: "Head of US Operations", role: "manager", since: "2024", relevance: "Feels the US payroll pain directly; good first conversation to validate the problem.", sourceIds: [4] },
  ],
  competitors: [
    { name: "project44", relationship: "direct", description: "Enterprise visibility platform.", strengths: "Brand and carrier network.", weaknesses: "Expensive for mid-market.", sourceIds: [13] },
    { name: "Magaya", relationship: "direct", description: "Forwarder operating system with US focus.", strengths: "Deep US customs.", weaknesses: "Dated UX.", sourceIds: [13] },
  ],
  swot: {
    strengths: ["Category leader in European mid-market forwarding", "118% net revenue retention", "Well-funded with patient investors"],
    weaknesses: ["Back-office systems lag headcount growth", "Thin US leadership bench", "Integration of Clearpath incomplete"],
    opportunities: ["US market is 3x the size of Europe for its segment", "Customs automation upsell"],
    threats: ["US incumbents respond on price", "Freight downturn hits forwarder budgets", "Multi-state compliance missteps"],
  },
  risks: [
    { title: "Incumbent renewal timing", description: "If the Dutch payroll contract renews in Q1 2027 for three years, the window closes. Confirm the term early.", severity: "high", likelihood: "medium", category: "timing", sourceIds: [9] },
    { title: "Finance team bandwidth", description: "The CFO is onboarding and finishing the Clearpath integration; a systems project may slip to 2027.", severity: "medium", likelihood: "medium", category: "execution", sourceIds: [5, 11] },
    { title: "US-only provider as a stopgap", description: "US ops may pick a local PEO quickly, fragmenting the stack and reducing the platform case.", severity: "medium", likelihood: "high", category: "competitive", sourceIds: [8] },
  ],
  sentiment: {
    overall: "mixed",
    themes: [
      { theme: "Growth and mission", sentiment: "positive", evidence: "Employees praise momentum, product quality and leadership transparency.", sourceIds: [8] },
      { theme: "Back-office friction", sentiment: "negative", evidence: "Late bonuses and expenses for US staff, manual onboarding paperwork.", sourceIds: [8] },
    ],
    ratings: [{ source: "Glassdoor", score: 4.1, scale: 5, count: 96, sourceIds: [8] }],
  },
  techStack: ["Workday HCM (HRIS, since 2024)", "NetSuite", "Salesforce", "Dutch payroll provider (unnamed in sources)", "Expensify"],
  purposeSections: [
    {
      id: "triggers",
      title: "Why now: trigger events",
      kind: "list",
      intro: "Three independent triggers converged in the last six months.",
      items: [
        { title: "Chicago office and 180 US hires", body: "Five US states by mid-2027 means multi-state tax registration, benefits enrolment and contractor conversions, none of which the current Dutch-run process handles well.", tag: "Sep 2026", badge: "high", sourceIds: [4] },
        { title: "New CFO with a systems mandate", body: "Jonas Keller said on the Finance Leaders podcast that his first year is about 'finance and people systems that scale across entities'. He led a similar programme at Adyen.", tag: "May 2026", badge: "high", sourceIds: [5] },
        { title: "Series C proceeds earmarked for operational foundations", body: "The funding announcement explicitly lists 'operational foundations' alongside US expansion and product.", tag: "Mar 2026", badge: "medium", sourceIds: [3] },
        { title: "Visible payroll pain in employee reviews", body: "Late bonuses and expense reimbursements for US staff are mentioned twice in 2026 reviews, both attributing it to payroll being run from the Netherlands.", tag: "Feb 2026", badge: "medium", sourceIds: [8] },
      ],
    },
    {
      id: "stakeholders",
      title: "Stakeholder map",
      kind: "cards",
      items: [
        { title: "Jonas Keller, CFO", body: "Economic buyer. Wants a board-reportable win in year one; cares about cost per employee, compliance risk and close speed.", tag: "Economic buyer", sourceIds: [5] },
        { title: "Sofia Marin, VP People", body: "Champion. Ran the 2024 HRIS switch to Workday; will care about employee experience and integration with Workday.", tag: "Champion", sourceIds: [7] },
        { title: "Daniel Oyelaran, COO", body: "Procurement owner. Prefers vendor consolidation; frame Helios as replacing a provider plus spreadsheets, not adding a tool.", tag: "Approver", sourceIds: [1] },
        { title: "Hannah Weiss, Head of US Operations", body: "Pain owner. Best first call to validate the US payroll and benefits friction before approaching the CFO.", tag: "Influencer", sourceIds: [4] },
      ],
    },
    {
      id: "pains",
      title: "Pain hypotheses",
      kind: "cards",
      items: [
        { title: "Multi-state US payroll run from Rotterdam", body: "Time-zone lag, manual tax registrations and late payments. Evidence: Glassdoor reviews and US job posts for a 'Payroll and Benefits Specialist' in Chicago.", badge: "high", sourceIds: [8, 9] },
        { title: "Entity sprawl after the Clearpath acquisition", body: "Four entities (NL, UK, DE, US) with different providers and reporting formats; the CFO's consolidation agenda implies month-end pain.", badge: "medium", sourceIds: [5, 11] },
        { title: "Workday integration gaps", body: "Payroll data is likely re-keyed between Workday and the payroll provider; Helios's native Workday connector is a direct answer.", badge: "medium", sourceIds: [7] },
      ],
    },
    {
      id: "angles",
      title: "Outreach angles",
      kind: "list",
      items: [
        { title: "To Sofia Marin (VP People)", body: "Congratulations on Chicago. When Mollie went from 300 to 900 you lived through multi-country payroll pain; with 180 US hires planned, is payroll across five states something your team is set up for yet?", copyable: true },
        { title: "To Jonas Keller (CFO)", body: "You mentioned on Finance Leaders that year one is about systems that scale across entities. Helios runs payroll for NL, UK, DE and US entities in one platform with Workday sync; happy to share what a consolidated close looks like for a 700-person company.", copyable: true },
        { title: "To Hannah Weiss (Head of US Ops)", body: "Saw the Chicago opening and the payroll specialist role. Teams we work with usually hit the multi-state wall around state four; would a 20-minute comparison of how others handled it be useful?", copyable: true },
      ],
    },
    {
      id: "discovery",
      title: "Discovery questions",
      kind: "list",
      items: [
        { title: "How is US payroll run today, and who owns it day to day?", body: "Validates the Rotterdam-run hypothesis and finds the pain owner." },
        { title: "When does the current payroll provider contract renew, and for how long?", body: "Determines the real deadline." },
        { title: "Which states will you have employees in by mid-2027?", body: "Sizes the multi-state compliance need." },
        { title: "How does payroll data get into Workday and NetSuite today?", body: "Surfaces integration and close-speed pain." },
        { title: "What would a successful first year look like for the new CFO on systems?", body: "Aligns the business case with his board narrative." },
        { title: "Did the Clearpath acquisition change how you run UK payroll?", body: "Tests entity-sprawl pain and consolidation appetite." },
      ],
    },
    {
      id: "objections",
      title: "Likely objections",
      kind: "qa",
      items: [
        { title: "We just changed HRIS; we are not ready for another systems project.", body: "Position Helios as the payroll layer that makes the Workday investment pay off, with a phased rollout starting with the US entity only." },
        { title: "A US PEO is faster for the Chicago ramp.", body: "Agree it is fast, then show the fragmentation cost by 2027: four providers, no consolidated reporting, and a migration anyway." },
        { title: "Our Dutch provider is fine for Europe.", body: "Keep it if they like; Helios can start with US and UK and consolidate Europe at renewal." },
      ],
    },
    {
      id: "landscape",
      title: "Vendors and competitors in the account",
      kind: "table",
      columns: ["Vendor", "Category", "Evidence", "Implication"],
      rows: [
        ["Workday", "HRIS", "Job posts require Workday experience; VP People led the 2024 switch.", "Lead with the native connector."],
        ["Unnamed Dutch provider", "Payroll (EU)", "Glassdoor reviews reference payroll run from the Netherlands.", "Likely incumbent; find the renewal date."],
        ["NetSuite", "ERP", "Finance job posts.", "Journal export matters to the CFO."],
        ["Expensify", "Expenses", "Employee reviews mention it.", "Late reimbursements are a payroll timing issue, not a tooling one."],
      ],
    },
  ],
  openQuestions: ["Exact renewal date and term of the Dutch payroll contract", "Whether a US PEO has already been engaged for the Austin office", "Who owns benefits administration in the US"],
  followUps: [
    { label: "Draft outreach email", prompt: "Draft a short, personalised outreach email to Sofia Marin, VP People at Lumen Freight Technologies, using the trigger events and pain hypotheses from the research report." },
    { label: "Discovery call plan", prompt: "Build a 30-minute discovery call plan for Lumen Freight Technologies: goals, hypotheses to validate, questions in order, and next-step ask." },
    { label: "More trigger events", prompt: "Find more trigger events at Lumen Freight Technologies from the last 90 days and update the Why now section." },
    { label: "Map buying committee", prompt: "Map the full buying committee at Lumen Freight Technologies with names, titles and LinkedIn URLs where available." },
  ],
  sources: [
    { id: 1, title: "About Lumen Freight", url: "https://www.lumenfreight.example/about", publisher: "Lumen Freight", date: "2026-09", type: "official", reliability: "high", note: "Company description, leadership, customer count" },
    { id: 2, title: "Lumen Freight Technologies - LinkedIn", url: "https://www.linkedin.com/company/lumenfreight-example", publisher: "LinkedIn", date: "2026-10", type: "database", reliability: "medium", note: "Headcount" },
    { id: 3, title: "Lumen Freight raises €140M Series C led by Atomico", url: "https://www.lumenfreight.example/news/series-c", publisher: "Lumen Freight newsroom", date: "2026-03-20", type: "official", reliability: "high", note: "ARR, NRR, use of proceeds" },
    { id: 4, title: "Dutch logistics unicorn Lumen Freight opens Chicago office, plans 180 US hires", url: "https://www.example-news.com/lumen-chicago", publisher: "Example Business News", date: "2026-09-18", type: "news", reliability: "high" },
    { id: 5, title: "Finance Leaders podcast: Jonas Keller on scaling finance at a €1B logistics company", url: "https://podcasts.example.com/finance-leaders/ep-212", publisher: "Finance Leaders", date: "2026-06-30", type: "other", reliability: "medium", note: "CFO priorities quote" },
    { id: 6, title: "Lumen Freight headcount history", url: "https://www.example-data.com/lumenfreight/headcount", publisher: "Example Data", date: "2026-09", type: "database", reliability: "medium" },
    { id: 7, title: "Sofia Marin - VP People - LinkedIn", url: "https://www.linkedin.com/in/sofiamarin-example", publisher: "LinkedIn", type: "social", reliability: "medium", note: "Background, HRIS project" },
    { id: 8, title: "Lumen Freight reviews", url: "https://www.glassdoor.example/Reviews/Lumen-Freight", publisher: "Glassdoor", date: "2026-10", type: "review", reliability: "low", note: "Sentiment themes, payroll complaints" },
    { id: 9, title: "Payroll and Benefits Specialist (Chicago) - job posting", url: "https://www.lumenfreight.example/careers/payroll-specialist-chicago", publisher: "Lumen Freight careers", date: "2026-09", type: "official", reliability: "high" },
    { id: 10, title: "Lumen Freight launches US customs automation", url: "https://www.lumenfreight.example/news/us-customs", publisher: "Lumen Freight newsroom", date: "2026-07-02", type: "official", reliability: "high" },
    { id: 11, title: "Lumen Freight acquires Clearpath Customs", url: "https://www.example-logistics-press.com/lumen-clearpath", publisher: "Example Logistics Press", date: "2025-11-15", type: "news", reliability: "high" },
    { id: 12, title: "Lumen Freight Technologies - funding rounds", url: "https://www.crunchbase.com/organization/lumen-freight-example", publisher: "Crunchbase", date: "2026-09", type: "database", reliability: "medium" },
    { id: 13, title: "Freight visibility software market map 2026", url: "https://www.example-research.com/freight-visibility-2026", publisher: "Example Research", date: "2026-05", type: "report", reliability: "medium" },
  ],
};
