/**
 * Reads the Vite-built single-file HTML views and writes them into a TypeScript
 * module, so the server (Node or Cloudflare Workers) can serve them as MCP
 * resources without touching the file system at runtime.
 */
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const views = ["onboarding", "report"] as const;

const entries = views.map((name) => {
  const file = path.join(root, "dist", "ui", `${name}.html`);
  if (!fs.existsSync(file)) {
    throw new Error(`Missing built view: ${file}. Run "npm run build:ui" first.`);
  }
  const html = fs.readFileSync(file, "utf8");
  return `  ${name}: ${JSON.stringify(html)},`;
});

const out = `// AUTO-GENERATED by scripts/embed-ui.ts. Do not edit by hand.
// Built: ${new Date().toISOString()}
export const UI_HTML = {
${entries.join("\n")}
} as const;

export type UiViewName = keyof typeof UI_HTML;
`;

const target = path.join(root, "src", "generated", "ui.ts");
fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target, out);
const sizes = views.map((v) => `${v}=${(fs.statSync(path.join(root, "dist", "ui", `${v}.html`)).size / 1024).toFixed(0)}KB`);
console.log(`[embed-ui] wrote ${path.relative(root, target)} (${sizes.join(", ")})`);
